"""create_visitor_logs_table

Revision ID: 2bf19aeb2704
Revises: 5d8e2a1f7c03
Create Date: 2026-03-18 16:09:43.767866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf19aeb2704'
down_revision: Union[str, Sequence[str], None] = '5d8e2a1f7c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.String(length=5), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=True),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pre_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('checked_in_by_id', sa.UUID(), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pre_approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_logs_resident_id'), 'visitor_logs', ['resident_id'], unique=False)
    op.create_index(op.f('ix_visitor_logs_society_id'), 'visitor_logs', ['society_id'], unique=False)
    op.create_index(op.f('ix_visitor_logs_unit_id'), 'visitor_logs', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_logs_unit_id'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_society_id'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_resident_id'), table_name='visitor_logs')
    op.drop_table('visitor_logs')
    # ### end Alembic commands ###
