"""add_units_table_and_user_unit_fk

Revision ID: 2f91e58ce8d9
Revises: fe54b529790e
Create Date: 2026-03-15 15:01:35.550648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f91e58ce8d9'
down_revision: Union[str, Sequence[str], None] = 'fe54b529790e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=True),
    sa.Column('floor_number', sa.String(length=20), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_society_id'), 'units', ['society_id'], unique=False)
    op.create_index('uq_unit_identity', 'units', ['society_id', sa.literal_column("COALESCE(block_name, '')"), sa.literal_column("COALESCE(floor_number, '')"), 'unit_number'], unique=True)
    op.add_column('users', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_unit_id'), 'users', ['unit_id'], unique=False)
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_unit_id'), table_name='users')
    op.drop_column('users', 'unit_id')
    op.drop_index('uq_unit_identity', table_name='units')
    op.drop_index(op.f('ix_units_society_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
