"""create_notices_table

Revision ID: a8eea61c74a2
Revises: 2bf19aeb2704
Create Date: 2026-03-22 13:57:57.393659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eea61c74a2'
down_revision: Union[str, Sequence[str], None] = '2bf19aeb2704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.String(length=5), nullable=False),
    sa.Column('posted_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_posted_by_id'), 'notices', ['posted_by_id'], unique=False)
    op.create_index(op.f('ix_notices_society_id'), 'notices', ['society_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_society_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_posted_by_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
